
CREATE TABLE raw_author(
    AUTHOR_ID SERIAL PRIMARY KEY,
    NAME TEXT
);

CREATE TABLE author(
    AUTHOR_ID SERIAL PRIMARY KEY,
    NAME TEXT UNIQUE
);

CREATE TABLE publication(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT);


CREATE TABLE article(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);


CREATE TABLE phdthesis(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);



CREATE TABLE book(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);




CREATE TABLE proceedings (
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);



CREATE TABLE website (
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);




CREATE TABLE incollection(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);



CREATE TABLE masterthesis(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);



create table inproceedings(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    AUTHOR_NAME TEXT,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    YEAR INT ,
    JOURNAL TEXT
);


CREATE TABLE authored(
    AUTHOR_NAME TEXT REFERENCES author(NAME),
    PUBLICATION_ID INT REFERENCES publication(PUBLICATION_ID)
);

