
CREATE TABLE raw_author(
    AUTHOR_ID SERIAL PRIMARY KEY,
    NAME TEXT UNIQUE
);

CREATE TABLE author(
    AUTHOR_ID SERIAL PRIMARY KEY,
    NAME TEXT UNIQUE
);

CREATE TABLE publication(
    PUBLICATION_ID SERIAL PRIMARY KEY,
    PUBKEY TEXT UNIQUE,
    TITLE TEXT,
    CONFERENCE TEXT,
    YEAR INT ,
    JOURNAL TEXT,
    IS_ARTICLE BOOLEAN,
    IS_PHDTHESIS BOOLEAN,
    IS_BOOK BOOLEAN,
    IS_PROCEEDINGS BOOLEAN,
    IS_WEBSITE BOOLEAN,
    IS_INCOLLECTION BOOLEAN,
    IS_MASTERTHESIS BOOLEAN,
    IS_INPROCEEDINGS BOOLEAN
);


CREATE TABLE authored(
    AUTHOR_ID INT REFERENCES author(AUTHOR_ID),
    PUBLICATION_ID INT REFERENCES publication(PUBLICATION_ID)
);

